/**
 * Calculate points on circle
 * generated by ChatGPT and customized by @phucbm
 * https://gist.github.com/phucbm/33a575a0ca43634df2edeb4b838c8a61
 *
 * @param numPoints
 * @param radius
 * @param startAngleInDegrees
 * @param clockwise
 * @returns {*[]}
 */
export function calculatePointsOnCircle(numPoints, radius, startAngleInDegrees = 0, clockwise = true){
    const points = [];
    const angleStep = (2 * Math.PI) / numPoints; //rad
    const direction = clockwise ? -1 : 1;

    // Convert start angle from degrees to radians and adjust it to ensure the first point starts at the specified angle
    const startAngleInRadians = -1 * (startAngleInDegrees * Math.PI) / 180; // convert degree to rad: degree * PI/180

    // Adjusting to start at the top
    const adjustedStartAngle = startAngleInRadians + Math.PI; // rad

    for(let i = 0; i < numPoints; i++){
        const angle = adjustedStartAngle + direction * i * angleStep;
        const rotate = (adjustedStartAngle - angle) * 180 / Math.PI; // rotate towards the center
        const x = radius + radius * Math.sin(angle);
        const y = radius + radius * Math.cos(angle);

        points.push({x, y, angle, rotate});
    }

    return points;
}