/**
 * Check boundaries for the ImageCarousel
 * generated by ChatGPT and customized by @vandangnhathung
 *
 * @param {React.MutableRefObject<number>} totalRef - Current total X offset.
 * @param {React.MutableRefObject<number>} totalWidthRef - Total width of all slide items.
 * @param {React.MutableRefObject<number>} containerWidthRef - Visible container width.
 * @param {React.MutableRefObject<boolean>} infiniteRef - Whether carousel is infinite.
 * @param {Function} setIsLeftDisabled - React setState to disable left button.
 * @param {Function} setIsRightDisabled - React setState to disable right button.
 * @returns {void}
 */

export function checkBoundaries(
    totalRef: React.MutableRefObject<number>,
    totalWidthRef: React.MutableRefObject<number>,
    containerWidthRef: React.MutableRefObject<number>,
    infiniteRef: React.MutableRefObject<boolean>,
    setIsLeftDisabled: React.Dispatch<React.SetStateAction<boolean>>,
    setIsRightDisabled: React.Dispatch<React.SetStateAction<boolean>>
  ): void {
    // === Infinite mode: no boundaries ===
    if (infiniteRef.current) {
      setIsLeftDisabled(false)
      setIsRightDisabled(false)
      return
    }
  
    // === Calculate maximum scroll value ===
    const maxScroll = -(totalWidthRef.current - containerWidthRef.current)
    const threshold = 5 // small buffer for precision rounding
  
    // === Update button states ===
    setIsLeftDisabled(totalRef.current >= -threshold)
    setIsRightDisabled(totalRef.current <= maxScroll + threshold)
  }
  